economiza/urls.py
from django.urls import path, include
from economiza import views


app_name = 'economiza'


urlpatterns = [
    path('', views.index, name='index'),
    path('cadastro/', views.register_user, name='register_user'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('extrato/', views.get_gastos, name='get_gastos'),
    path('gastos/adicionar', views.GastoCreateView.as_view(), name='add_gasto'),
    path('gastos/apagar/<int:pk>', views.GastoDeleteView.as_view(), name='delete_gasto'),
    path('salvar-limite/', views.save_limits, name='save_limits'),
    path('extrato/select_month_year_and_category/', views.select_month_year_and_category, name='selected_month'),
    path('sobre/', views.about, name='about')
]

teste_inoa/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('economiza.urls'))
]

economiza/models.py
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django import template
    
register = template.Library()


# Create your models here.
class Categoria(models.Model):

    categoria_nome = models.CharField(max_length=128)
    limite_categoria = models.IntegerField(null=True, blank=True)
    user = models.ForeignKey(User, related_name='categoria', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.categoria_nome


class Perfil(models.Model):
    SEXO_CHOICES = [
        ["F", "Feminino"],
        ["M", "Masculino"],
        ["N", "Nenhuma das opções"]
    ]

    nome = models.CharField(max_length=128, null=False)
    sobrenome = models.CharField(max_length=128, null=False)
    sexo = models.CharField(max_length=1, choices=SEXO_CHOICES)
    idade = models.IntegerField(null=True)
    telefone = models.CharField(max_length=20, blank=True)
    email = models.EmailField(null=False, unique=True)
    user = models.OneToOneField(User, related_name='perfil', on_delete=models.CASCADE)
    limite = models.PositiveIntegerField(null=True)
    criado_em = models.DateTimeField('criado em', auto_now_add=True)

    class Meta:
        ordering = ['criado_em']
        verbose_name = (u'Perfil')
        verbose_name_plural = (u'Perfis')

    def __unicode__(self):
        return self.nome

    def get_absolute_url(self):
        return reverse('economiza:get_gastos', kwargs={'pk': self.pk})


class Gasto(models.Model):
  
    data_do_gasto = models.DateField(null=True)
    categoria = models.ForeignKey(Categoria, related_name='gasto', on_delete=models.CASCADE)
    descricao = models.CharField(max_length=150)
    preco = models.FloatField()
    quantidade = models.PositiveIntegerField()
    user = models.ForeignKey(User, related_name='gasto', on_delete=models.CASCADE, null=True)

    @register.filter
    def total_item_filter(self):
        return  self.quantidade * self.preco

    @property
    def limite_modify(self):
        return self.limite - self.total_item_filter





    

economiza/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import Perfil, Gasto, Categoria
from django.contrib.auth.models import User
from bootstrap_modal_forms.forms import BSModalForm
from bootstrap_datepicker_plus import DatePickerInput
from tempus_dominus.widgets import DatePicker


class PerfilForm(forms.ModelForm):
    class Meta:
        model = Perfil
        fields = ['nome', 'sobrenome', 'sexo', 'idade', 'email', 'telefone']

class UserForm(forms.ModelForm):

    username = forms.CharField(max_length=128)
    password = forms.CharField(max_length=128, widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'password']

class GastoForm(BSModalForm):
    quantidade = forms.IntegerField(initial=1)
    data_do_gasto = forms.DateTimeField(widget=DatePicker(
        options={
            'format': 'D/MM/Y',
        },
        attrs={
            'append': 'fa fa-calendar',
            'icon_toggle': True,
        }
    ), input_formats=('%d/%m/%Y', ))
    class Meta:
        model = Gasto
        fields = ['data_do_gasto', 'categoria', 'descricao', 'preco', 'quantidade']
        ordering = ('data_do_gasto',)








        

economiza/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.edit import CreateView, UpdateView
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect, QueryDict
from django.contrib.auth.decorators import login_required
from bootstrap_modal_forms.generic import BSModalCreateView, BSModalDeleteView
from .models import Perfil, Gasto, Categoria
from .forms import PerfilForm, UserForm, GastoForm
from django.contrib import messages
from django.db.models import F
from django.views.decorators.csrf import csrf_exempt
import json
import datetime



today = datetime.date.today()
# Create your views here.
def index(request):
    categorias = None
    value_limit_global = 0
    limit_by_category_id = {}
    has_at_least_one_category_limit = False
    if not request.user.is_anonymous:
        categorias = Categoria.objects.filter(user=request.user)
        value_limit_global = Perfil.objects.get(user=request.user).limite

        for categoria in categorias:
            limit_by_category_id[categoria.id] = categoria.limite_categoria
            if categoria.limite_categoria:
                has_at_least_one_category_limit = True

    return render(request,'economiza/index.html', {'categorias': categorias,
                                                   'value_limit_global': value_limit_global, 
                                                   'limit_by_category_id': limit_by_category_id})
                                                #    'has_at_least_one_category_limit': has_at_least_one_category_limit})

def about(request):
    return render(request, 'economiza/about.html')

def register_user(request):

    registered = False

    basic_categories = [u"Alimentação", u"Despesas do Lar", u"Lazer", u"Transporte", u"Outros"]

    if request.method == 'POST':

        user_form = UserForm(request.POST)
        perfil_form = PerfilForm(request.POST)

        if perfil_form.is_valid() and user_form.is_valid():
            user = user_form.save()
            perfil = perfil_form.save(commit = False)
            perfil.user = user
            user.set_password(user.password)
            user.save()
            perfil.save()
            for category_name in basic_categories:
                category = Categoria(categoria_nome=category_name,
                                      user=user)
                category.save()
            

            registered = True
            login(request,user)

            return HttpResponseRedirect(reverse('economiza:index'))
        else:
            print(user_form.errors)
    else:

       user_form = UserForm() 
       perfil_form = PerfilForm()

    return render(request, 'economiza/cadastro.html', {'user_form': user_form, 'registered': registered, 'perfil_form': perfil_form})

def user_login(request):

    if request.method == 'POST':
     
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user:
        
            if user.is_active:
    
                login(request,user)
               
                return HttpResponseRedirect(reverse('economiza:index'))
            else:
    
                return HttpResponse("Your account is not active.")
        else:
            print("Erro ao login.")
            print("Campos: username: {} e password: {}".format(username,password))
            messages.error(request,'Usuário ou senha está incorreto!')
            return render(request, 'economiza/login.html')

    else:
        return render(request, 'economiza/login.html', {})


@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('economiza:index'))

@csrf_exempt
@login_required
def get_gastos(request):
     
    list_gastos = Gasto.objects.filter(user=request.user, data_do_gasto__month=today.month).order_by('data_do_gasto')        
    list_limits_categories = Categoria.objects.filter(user=request.user)
    gasto_form = GastoForm(request.POST)

    return render(request, 'economiza/gastos.html', {'gastos': list_gastos, 'gasto_form': gasto_form,
     'limites_categorias': list_limits_categories})


@csrf_exempt
@login_required
def select_month_year_and_category(request):
    
    if request.method == 'GET' and request.is_ajax():
        
        
        selected_month = request.GET['selected_month']
        selected_year = request.GET['selected_year']
        selected_category = request.GET['selected_category']
       
      
        if selected_month == '0' and selected_year == '0' and selected_category == '0':
            list_gastos = Gasto.objects.filter(user=request.user).order_by('data_do_gasto')
            

        if selected_month != '0' and selected_year == '0' and selected_category == '0': 
            list_gastos = Gasto.objects.filter(user=request.user, data_do_gasto__month=selected_month).order_by('data_do_gasto')
          

        if selected_year != '0' and selected_month == '0' and selected_category == '0':
            list_gastos = Gasto.objects.filter(user=request.user, data_do_gasto__year=selected_year).order_by('data_do_gasto')


        if selected_category != '0' and selected_month == '0' and selected_year == '0':
            list_gastos = Gasto.objects.filter(user=request.user, categoria__id=selected_category).order_by('data_do_gasto')

        if selected_category != '0' and selected_month != '0' and selected_year == '0':
            list_gastos = Gasto.objects.filter(user=request.user, data_do_gasto__month=selected_month,
                                                                  categoria__id=selected_category).order_by('data_do_gasto')

        if selected_category != '0' and selected_month == '0' and selected_year != '0':
            list_gastos = Gasto.objects.filter(user=request.user, data_do_gasto__year=selected_year,
                                                                  categoria__id=selected_category).order_by('data_do_gasto')

        if selected_year != "0" and selected_month != "0" and selected_category != "0":
            list_gastos = Gasto.objects.filter(user=request.user, data_do_gasto__month=selected_month,
                                                                  data_do_gasto__year=selected_year,
                                                                  categoria__id=selected_category).order_by('data_do_gasto')

        if selected_year != "0" and selected_month != "0" and selected_category == "0":
            list_gastos = Gasto.objects.filter(user=request.user, data_do_gasto__month=selected_month,
                                                                  data_do_gasto__year=selected_year).order_by('data_do_gasto')
    
    list_limits_categories = Categoria.objects.filter(user=request.user)
    gasto_form = GastoForm(request.POST)

    return render(request, 'economiza/filter_month_year_and_category.html', {'gastos': list_gastos, 'gasto_form': gasto_form,
     'limites_categorias': list_limits_categories})

@csrf_exempt
@login_required
def select_category(request):
    
    if request.method == 'GET' and request.is_ajax():
        selected_category = request.GET['selected_category']
        if selected_category == '0':
            list_limits_categories = Categoria.objects.filter(user=request.user)
        else:
            list_gastos = Gasto.objects.filter(user=request.user).order_by('data_do_gasto')
            list_limits_categories = Categoria.objects.filter(user=request.user, id__month=selected_month)
    else:
        selected_month = ''
        list_gastos = Gasto.objects.filter(user=request.user).order_by('data_do_gasto')

    
    
    gasto_form = GastoForm(request.POST)

    return render(request, 'economiza/filter_category.html', {'gastos': list_gastos, 'gasto_form': gasto_form,
     'limites_categorias': list_limits_categories})



class GastoCreateView(LoginRequiredMixin, BSModalCreateView):
    template_name = 'economiza/gasto_form.html'
    form_class = GastoForm
    success_url = reverse_lazy('economiza:get_gastos')


    def get_form(self, *args, **kwargs):
        form = super(GastoCreateView, self).get_form(*args, **kwargs)
        form.fields['categoria'].queryset = Categoria.objects.filter(user=self.request.user)
        return form

    def form_valid(self, form):
        form.instance.user_id = self.request.user.pk
        return super().form_valid(form)

class GastoDeleteView(BSModalDeleteView):
    model = Gasto
    template_name = 'economiza/delete_gasto.html'
    success_url = reverse_lazy('economiza:get_gastos')
    success_message = ""



from django.template.defaulttags import register
@register.filter
def get_item(dictionary, key):
    return dictionary.get(key) if dictionary.get(key) else ""


@login_required
def save_limits(request):

    if request.method=='POST' and request.is_ajax():
        value_global_limit = request.POST['value_global_limit']
        limit_by_category_id =  json.loads(request.POST['limit_by_category_id'])
        
        
        perfil = Perfil.objects.filter(user=request.user)
        perfil.update(limite=value_global_limit)

        categorias = Categoria.objects.filter(user=request.user)
        for categoria in categorias:
            categoria.limite_categoria = limit_by_category_id[str(categoria.pk)] or 0
            categoria.save()
        
        return HttpResponseRedirect(reverse('economiza:get_gastos'))
    
            
            
        

economiza/templates/economiza/about.html
{% extends "economiza/base.html" %}
{% block body_block %}
{% load static %}
<div class="jumbotron">
    <h1 class="text-center">Economiza! <img src="{% static 'images/icons/money.png' %}" style="height: 50px;"></h1>
    <h2 class="text-center" style="margin-top: 50px">Um sistema feito com o objetivo de controlar seus gastos mensais,
         podendo assim ter uma liberdade financeira! <img src="{% static 'images/icons/fly-money.png' %}" style="height: 50px;"></h2>
    <h3 class="text-right" style="margin-top: 50px;">Criado por: Gabriel Kerchner</h3>
</div>
{% endblock body_block %}

economiza/templates/economiza/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Economiza!</title>

        <link rel="stylesheet" href="{% static 'css/dragdealer.css' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <!--Plugin CSS file with desired skin-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.0/css/ion.rangeSlider.min.css"/>
        
        <!--jQuery-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        
        <!--Plugin JavaScript file-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.0/js/ion.rangeSlider.min.js"></script>
    
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

         <!-- Moment.js -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js" integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>

        <!-- Tempus Dominus Bootstrap 4 -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js" integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.css">


        <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
        <script src="{% static 'js/dragdealer.js' %}"></script>
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <script src="{% static 'js/main.js' %}"></script>
        <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" />
    </head>
    <body>
        
        <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #4d0270">
            <a class="navbar-brand" href="{% url 'economiza:index' %}"><img src="{% static 'images/icons/money.png' %}" id="icon">
              Economiza!
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'economiza:index' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'economiza:get_gastos' %}">Extrato</a>
                </li>
                {% endif %}   
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'economiza:about' %}">Sobre</a>
                </li>
              </ul>
              {% if user.is_authenticated %}
              <div class="dropdown show">
                <a href="#" class="btn btn-info mr-sm-2 my-2 my-lg-0 dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <img src=" {% static 'images/icons/man-user.png' %}" id="icon_invert" alt="">
                  <span>Olá {{user.perfil.nome}}</span>
                </a>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'economiza:user_logout' %}">Sair</a>
                </div>
              </div>
              {% else %}
              <a href="{% url 'economiza:user_login' %}" class="btn btn-info mr-sm-2 my-2 my-lg-0" role='button'>
                <img src=" {% static 'images/icons/man-user.png' %}" id="icon_invert" alt="">
                <span> Login</span>
              </a>
              <a href="{% url 'economiza:register_user' %}" class="btn btn-info mr-sm-2 my-2 my-lg-0" role='button'>
                <img src=" {% static 'images/icons/new-user.png' %}" id="icon_invert" alt="">
                <span> Cadastre-se</span>
              </a>
              {% endif %}
            </div>
          </nav>
          <div class="container">
            {% block body_block %}
            {% endblock %}
        </div>
    </body>
</html>

economiza/templates/economiza/delete_gasto.html
{% load crispy_forms_tags %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Apagar Gasto</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">
    <p class="delete-text">Tem certeza que deseja excluir o item 
      <strong>{{ gasto.descricao }}</strong>?</p>
  </div>

  <div class="modal-footer">
    <button type="submit" class="delete-btn btn btn-danger">Apagar</button>
  </div>

</form>

economiza/templates/economiza/filter_month_year_and_category.html
{% load static %}
<table class="table table-hover table-dark text-center" id="gasto_table1">
    <thead>
        <tr>
        <th scope="col">Data</th>
        <th scope="col">Categoria</th>
        <th scope="col">Descrição</th>
        <th scope="col">Preço (R$)</th>
        <th scope="col">Quantidade</th>
        <th scope="col">Total (R$)</th>
        <th scope="col">Excluir</th>
        </tr>
    </thead>
    {% if gastos %}
    {% for gasto in gastos %}
    <tbody class="text-center" style="background-color: #525252">
        <tr>
        <td>{{gasto.data_do_gasto}}</td>
        <td id="{{gasto.categoria.id}}" class="id_category_table" data-id='{{gasto.categoria.id}}'>{{gasto.categoria.categoria_nome}}</td>
        <td>{{gasto.descricao}}</td>
        <td style="color: #85bb65">{{gasto.preco|floatformat:2}}</td>
        <td>{{gasto.quantidade}}x</td>
        <td class='total_field' id="total_field_{{gasto.categoria.id}}" data-id='{{gasto.categoria.id}}' style="color: #85bb65">{{gasto.total_item_filter|floatformat:2}}</td>
        <td>
        <button type="button" class="delete_gasto btn btn-sm btn-danger" data-id="{% url 'economiza:delete_gasto' gasto.pk %}" style="background-color: transparent; border: none !important;">
            <img src="{% static 'images/icons/x-button.png' %}" style="height: 20px;" alt="">
        </button></td>
        </tr>
        <div id="update_table_gasto"></div>
    </tbody>
    {% endfor %}
    {% else %}
    <h3>Nenhum gasto cadastrado!</h3>
    {% endif %}

</table>
   

<div class="modal fade" tabindex="-1" role="dialog" id="modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content"></div>
    </div>
</div>

economiza/templates/economiza/gastos.html
{% extends "economiza/base.html" %}
{% block body_block %}
{% load static %}

<div class="box">
    <div class="row">
        <div class="col-4">
            <h3 style="margin-top: 50px;">Mensal: {% if user.perfil.limite %} R$ {% endif %}<span id='limit_globe'style="color: #85bb65">{{user.perfil.limite}}</span></h3>
        </div>
        <div class="col-4" style="margin-left: -60px">
            {% if limites_categorias %}
            <h3 style="margin-bottom: 30px" class="text-right"><strong>Limites Disponíveis</strong></h3>
            {% for limite in limites_categorias %}
            <h4 class="text-right"><span id="category-limit" class="text-center">{{limite.categoria_nome}}</span>: {% if limite.limite_categoria %} R$ {% endif %}<span class="category_limit_id text-right" id="value_category_limit_{{limite.id}}" data-id="{{limite.id}}" style="color: #85bb65;">{{limite.limite_categoria}}<br></span></h4>
            {% endfor %}
            {% endif %}
        </div>
        <div class="col-4" style="margin-left: 60px">
            <button type="button" style="margin-top: 60px;" class="btn btn-info" id="add_gasto" data-url="{% url 'economiza:add_gasto' %}"><img src="{% static 'images/icons/shopping-cart-add-button.png' %}" id="icon" style=" filter: invert(1);"> Adicionar um gasto</button>
        </div>
    </div>
</div>

<div id="limit_globe_filter" style="display: none"></div>
<div id="total" style="display: none"></div>
<table class="table table-hover table-dark text-center" id="gasto_table">
    <thead>
        <tr>
        <th scope="col">Data</th>
        <th scope="col">Categoria</th>
        <th scope="col">Descrição</th>
        <th scope="col">Preço (R$)</th>
        <th scope="col">Quantidade</th>
        <th scope="col">Total (R$)</th>
        <th scope="col">Excluir</th>
        </tr>
    </thead>
    {% if gastos %}
    <div class="row">
        <div class="col-4">
            <div class="form-group">
                <h5 for='sel2'><img src="{% static 'images/icons/magnifier.png' %}" style="height: 25px;"> Filtrar por Categoria:</h5>
                <select class="form-control" id="filter_category">
                    <option value="0">Todas</option>
                    {% for categoria in limites_categorias %}
                    <option value="{{categoria.id}}">{{categoria.categoria_nome}}</option>
                    {% endfor %}
                </select>
            </div>
            </div>
        <div class="col-4">
            <div class="form-group">
                <h5 for="sel1"><img src="{% static 'images/icons/magnifier.png' %}" style="height: 25px;"> Filtrar por Mês: </h5>
                <select class="form-control" id="filter_month">
                    <option value="0">Todos</option>
                    <option value="1">Janeiro</option>
                    <option value="2">Fevereiro</option>
                    <option value="3">Março</option>
                    <option value="4">Abril</option>
                    <option value="5">Maio</option>
                    <option value="6">Junho</option>
                    <option value="7">Julho</option>
                    <option value="8" selected>Agosto</option>
                    <option value="9">Setembro</option>
                    <option value="10">Outubro</option>
                    <option value="11">Novembro</option>
                    <option value="12">Dezembro</option>
                </select>
            </div>
        </div>
        <div class="col-4">
            <div class="form-group">
                <h5 for='sel3'><img src="{% static 'images/icons/magnifier.png' %}" style="height: 25px;"> Filtrar por Ano:</h5>
                <select class="form-control" id="filter_year">
                    <option value="0">Todos</option>
                    {% for gasto in gastos %}
                    {% ifchanged gasto.data_do_gasto.year %} 
                    <option value="{{gasto.data_do_gasto.year}}" selected>{{gasto.data_do_gasto.year}}</option>
                    {% endifchanged %}
                    {% endfor %}
                </select>
            </div>
        </div>
        
    </div>
    
    {% for gasto in gastos %}
    <tbody class="text-center" style="background-color: #525252"> 
        <tr>
        <td>{{gasto.data_do_gasto}}</td>
        <td id="{{gasto.categoria.id}}" class="id_category_table" data-id='{{gasto.categoria.id}}'>{{gasto.categoria.categoria_nome}}</td>
        <td>{{gasto.descricao}}</td>
        <td style="color: #85bb65">{{gasto.preco|floatformat:2}}</td>
        <td>{{gasto.quantidade}}x</td>
        <td class='total_field' id="total_field_{{gasto.categoria.id}}" data-id='{{gasto.categoria.id}}' style="color: #85bb65">{{gasto.total_item_filter|floatformat:2}}</td>
        <td>
        <button type="button" class="delete_gasto btn btn-sm btn-danger" data-id="{% url 'economiza:delete_gasto' gasto.pk %}" style="background-color: transparent; border: none !important;">
            <img src="{% static 'images/icons/x-button.png' %}" style="height: 20px;" alt="">
        </button></td>
        </tr>
        <div id="update_table_gasto"></div>
    </tbody>
    {% endfor %}
    {% else %}
    <h3>Nenhum gasto cadastrado!</h3>
    {% endif %}

</table>
   

<div class="modal fade" tabindex="-1" role="dialog" id="modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content"></div>
    </div>
</div>
    

{% endblock body_block %}

economiza/templates/economiza/login.html
{% extends "economiza/base.html" %}
{% block body_block %}
<div class="container">
    <div class="jumbotron" style="margin-top: 40px;">
      <h1>Login</h1>

        <form method="post" action="{% url 'economiza:user_login' %}" class="form-inline">
          {% csrf_token %}
          <label class="sr-only" for="username">Username</label>
            <div class="input-group mb-2 mr-sm-2">
                <div class="input-group-prepend">
                    <div class="input-group-text">@</div>
                </div>
                <input type="text" class="form-control" id="username" name='username' placeholder="Username" maxlength="128">
                <p><small class="caracteres"></small></p> 
            </div>

          <label class="sr-only" for="password"></label>
          <input class="form-control mb-2 mr-sm-2" type="password" name="password" placeholder="Password" maxlength="128">

          <input class="btn btn-primary" type="submit" name="" value="Login" style="margin-bottom: 10px;">

        </form>
        {% for message in messages %}

          <div class="alert alert-danger">
            

              {{ message }}

          </div>
            {% endfor %}
    </div>
  </div>
{% endblock body_block %}